services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: "Europe/Moscow"
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: "${WEBPASSWORD}"
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: "ALL"
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./etc-pihole:/etc/pihole"
    configs:
      - source: custom_list
        target: /etc/pihole/custom.list
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN

      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      # - SYS_TIME

      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.${HOST_NAME}.local`)
      - traefik.http.routers.pihole.entrypoints=web
      - traefik.http.services.pihole.loadbalancer.server.port=80
    networks:
      - default
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true

configs:
  custom_list:
    content: |
      ${HOST_IP} uptime.${HOST_NAME}.local
      ${HOST_IP} git.${HOST_NAME}.local
      ${HOST_IP} pihole.${HOST_NAME}.local
      ${HOST_IP} dashboard.${HOST_NAME}.local
