services:
  kuma:
    container_name: kuma
    image: louislam/uptime-kuma:2
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma.rule=Host(`uptime.${HOST_NAME}.local`)
      - traefik.http.routers.kuma.entrypoints=web
      - traefik.http.services.kuma.loadbalancer.server.port=3001
    networks:
      - default
      - traefik
    restart: unless-stopped

volumes:
  uptime-kuma:

networks:
  traefik:
    external: true
